### ISSUE TITLE
16 bit?

### ISSUE THREAD

**Issue by javafun** [michaelmcdaniel/GuidgenConsole#1]
C:>GuidGen.exe /?
This version of C:\GuidGen.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of
the program, and then contact the software publisher.

**Comment by michaelmcdaniel** [comment]
Really only intended to run with .net 4.0

**Comment by michaelmcdaniel** [comment]
Added .NET v2.0 compatible binaries/project.  Since no target OS (I'm assuming XP) was specified, this should run now if at least .NET 2.0 is available.
